import localFont from "next/font/local";
import "./globals.css";
import Footer from "./component/footer/footer";
import { AuthProvider } from "./Provider";
import {UserProvider} from '@/app/UserContext'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <script src="https://upload-widget.cloudinary.com/latest/global/all.js" type="text/javascript">  
      </script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
        <UserProvider>
      
        <div style={{heigth:'80vh'}}>{children}</div>
          <Footer />
  
        </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
